export default {
  additionalType: "",
  alternateName: "",
  description: "",
  disambiguatingDescription: "",
  identifier: "actionAccessSpecification",
  image: "",
  mainEntityOfPage: "ActionAccessSpecification",
  name: "",
  potentialAction: "",
  sameAs: "",
  subjectOf: "",
  url: "",
  ItemList: {
    itemListElement: [],
    itemListOrder: "",
    numberOfItems: 0,
  },
  ActionAccessSpecification: {
    availabilityEnds: "",
    availabilityStarts: "",
    category: "",
    eligibleRegion: "",
    expectsAcceptanceOf: "",
    ineligibleRegion: "",
    requiresSubscription: 0,
  },
  Intangible: {},
}
